import { StyledValue } from "src/@types/table";
import {
  ILocation,
  IOrder,
  IStatusesApproval,
  IStatusesShip,
} from "src/@types/user";

export const STATUSES_APPROVAL: Record<IStatusesApproval, StyledValue> = {
  [IStatusesApproval.APPROVED]: {
    style: {
      color: "#008767",
    },
    value: "Approved",
  },
  [IStatusesApproval.PENDING]: {
    style: {
      color: "#FFB700",
    },
    value: "Pending",
  },
  [IStatusesApproval.REJECTED]: {
    style: {
      color: "#DF0404",
    },
    value: "Rejected",
  },
};

export const STATUSES_SHIPS: Record<IStatusesShip, StyledValue> = {
  [IStatusesShip.SHIPPED]: {
    style: {
      color: "#008767",
    },
    value: "Shipped",
  },
  [IStatusesShip.PENDING]: {
    style: {
      color: "#FFB700",
    },
    value: "Pending",
  },
  [IStatusesShip.CANCELED]: {
    style: {
      color: "#DF0404",
    },
    value: "Canceled",
  },
};

export const ORDER_DATA: IOrder[] = [
  {
    key: "1",
    salesOrder: "1111111",
    poDate: "08/13/24",
    shipTo: "Location Name A",
    amount: "$325.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111111",
  },
  {
    key: "2",
    salesOrder: "1111112",
    poDate: "08/13/24",
    shipTo: "Location Name B",
    amount: "$215.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111112",
  },
  {
    key: "3",
    salesOrder: "1111113",
    poDate: "08/13/24",
    shipTo: "Location Name C",
    amount: "$140.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111113",
  },
  {
    key: "4",
    salesOrder: "1111114",
    poDate: "08/13/24",
    shipTo: "Location Name D",
    amount: "$49.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111114",
  },
  {
    key: "5",
    salesOrder: "1111115",
    poDate: "08/13/24",
    shipTo: "Location Name E",
    amount: "$64.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111115",
  },
  {
    key: "6",
    salesOrder: "1111116",
    poDate: "08/13/24",
    shipTo: "Location Name F",
    amount: "$72.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111116",
  },
  {
    key: "7",
    salesOrder: "1111117",
    poDate: "08/13/24",
    shipTo: "Location Name G",
    amount: "$25.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111117",
  },
  {
    key: "8",
    salesOrder: "1111118",
    poDate: "08/13/24",
    shipTo: "Location Name H",
    amount: "$80.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111118",
  },
  {
    key: "9",
    salesOrder: "1111119",
    poDate: "08/13/24",
    shipTo: "Location Name I",
    amount: "$300.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111119",
  },
  {
    key: "10",
    salesOrder: "1111120",
    poDate: "08/13/24",
    shipTo: "Location Name J",
    amount: "$500.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111120",
  },
  {
    key: "11",
    salesOrder: "1111121",
    poDate: "08/13/24",
    shipTo: "Location Name K",
    amount: "$150.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111121",
  },
  {
    key: "12",
    salesOrder: "1111122",
    poDate: "08/13/24",
    shipTo: "Location Name L",
    amount: "$200.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111122",
  },
  {
    key: "13",
    salesOrder: "1111123",
    poDate: "08/13/24",
    shipTo: "Location Name M",
    amount: "$420.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111123",
  },
  {
    key: "14",
    salesOrder: "1111124",
    poDate: "08/13/24",
    shipTo: "Location Name N",
    amount: "$65.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111124",
  },
  {
    key: "15",
    salesOrder: "1111125",
    poDate: "08/13/24",
    shipTo: "Location Name O",
    amount: "$115.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111125",
  },
  {
    key: "16",
    salesOrder: "1111126",
    poDate: "08/13/24",
    shipTo: "Location Name P",
    amount: "$98.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111126",
  },
  {
    key: "17",
    salesOrder: "1111127",
    poDate: "08/13/24",
    shipTo: "Location Name Q",
    amount: "$76.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111127",
  },
  {
    key: "18",
    salesOrder: "1111128",
    poDate: "08/13/24",
    shipTo: "Location Name R",
    amount: "$130.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111128",
  },
  {
    key: "1111",
    salesOrder: "1111111",
    poDate: "08/13/24",
    shipTo: "Location Name A",
    amount: "$325.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111111",
  },
  {
    key: "21",
    salesOrder: "1111112",
    poDate: "08/13/24",
    shipTo: "Location Name B",
    amount: "$215.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111112",
  },
  {
    key: "31",
    salesOrder: "1111113",
    poDate: "08/13/24",
    shipTo: "Location Name C",
    amount: "$140.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111113",
  },
  {
    key: "41",
    salesOrder: "1111114",
    poDate: "08/13/24",
    shipTo: "Location Name D",
    amount: "$49.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111114",
  },
  {
    key: "51",
    salesOrder: "1111115",
    poDate: "08/13/24",
    shipTo: "Location Name E",
    amount: "$64.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111115",
  },
  {
    key: "61",
    salesOrder: "1111116",
    poDate: "08/13/24",
    shipTo: "Location Name F",
    amount: "$72.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111116",
  },
  {
    key: "71",
    salesOrder: "1111117",
    poDate: "08/13/24",
    shipTo: "Location Name G",
    amount: "$25.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111117",
  },
  {
    key: "81",
    salesOrder: "1111118",
    poDate: "08/13/24",
    shipTo: "Location Name H",
    amount: "$80.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111118",
  },
  {
    key: "91",
    salesOrder: "1111119",
    poDate: "08/13/24",
    shipTo: "Location Name I",
    amount: "$300.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111119",
  },
  {
    key: "101",
    salesOrder: "1111120",
    poDate: "08/13/24",
    shipTo: "Location Name J",
    amount: "$500.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111120",
  },
  {
    key: "111",
    salesOrder: "1111121",
    poDate: "08/13/24",
    shipTo: "Location Name K",
    amount: "$150.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111121",
  },
  {
    key: "121",
    salesOrder: "1111122",
    poDate: "08/13/24",
    shipTo: "Location Name L",
    amount: "$200.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111122",
  },
  {
    key: "131",
    salesOrder: "1111123",
    poDate: "08/13/24",
    shipTo: "Location Name M",
    amount: "$420.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111123",
  },
  {
    key: "141",
    salesOrder: "1111124",
    poDate: "08/13/24",
    shipTo: "Location Name N",
    amount: "$65.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111124",
  },
  {
    key: "151",
    salesOrder: "1111125",
    poDate: "08/13/24",
    shipTo: "Location Name O",
    amount: "$115.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111125",
  },
  {
    key: "161",
    salesOrder: "1111126",
    poDate: "08/13/24",
    shipTo: "Location Name P",
    amount: "$98.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111126",
  },
  {
    key: "171",
    salesOrder: "1111127",
    poDate: "08/13/24",
    shipTo: "Location Name Q",
    amount: "$76.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111127",
  },
  {
    key: "181",
    salesOrder: "1111128",
    poDate: "08/13/24",
    shipTo: "Location Name R",
    amount: "$130.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111128",
  },
  {
    key: "12",
    salesOrder: "1111111",
    poDate: "08/13/24",
    shipTo: "Location Name A",
    amount: "$325.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111111",
  },
  {
    key: "22",
    salesOrder: "1111112",
    poDate: "08/13/24",
    shipTo: "Location Name B",
    amount: "$215.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111112",
  },
  {
    key: "32",
    salesOrder: "1111113",
    poDate: "08/13/24",
    shipTo: "Location Name C",
    amount: "$140.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111113",
  },
  {
    key: "42",
    salesOrder: "1111114",
    poDate: "08/13/24",
    shipTo: "Location Name D",
    amount: "$49.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111114",
  },
  {
    key: "52",
    salesOrder: "1111115",
    poDate: "08/13/24",
    shipTo: "Location Name E",
    amount: "$64.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111115",
  },
  {
    key: "62",
    salesOrder: "1111116",
    poDate: "08/13/24",
    shipTo: "Location Name F",
    amount: "$72.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111116",
  },
  {
    key: "72",
    salesOrder: "1111117",
    poDate: "08/13/24",
    shipTo: "Location Name G",
    amount: "$25.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111117",
  },
  {
    key: "82",
    salesOrder: "1111118",
    poDate: "08/13/24",
    shipTo: "Location Name H",
    amount: "$80.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111118",
  },
  {
    key: "92",
    salesOrder: "1111119",
    poDate: "08/13/24",
    shipTo: "Location Name I",
    amount: "$300.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111119",
  },
  {
    key: "102",
    salesOrder: "1111120",
    poDate: "08/13/24",
    shipTo: "Location Name J",
    amount: "$500.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111120",
  },
  {
    key: "112",
    salesOrder: "1111121",
    poDate: "08/13/24",
    shipTo: "Location Name K",
    amount: "$150.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111121",
  },
  {
    key: "122",
    salesOrder: "1111122",
    poDate: "08/13/24",
    shipTo: "Location Name L",
    amount: "$200.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111122",
  },
  {
    key: "132",
    salesOrder: "1111123",
    poDate: "08/13/24",
    shipTo: "Location Name M",
    amount: "$420.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111123",
  },
  {
    key: "142",
    salesOrder: "1111124",
    poDate: "08/13/24",
    shipTo: "Location Name N",
    amount: "$65.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111124",
  },
  {
    key: "152",
    salesOrder: "1111125",
    poDate: "08/13/24",
    shipTo: "Location Name O",
    amount: "$115.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111125",
  },
  {
    key: "162",
    salesOrder: "1111126",
    poDate: "08/13/24",
    shipTo: "Location Name P",
    amount: "$98.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111126",
  },
  {
    key: "172",
    salesOrder: "1111127",
    poDate: "08/13/24",
    shipTo: "Location Name Q",
    amount: "$76.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111127",
  },
  {
    key: "182",
    salesOrder: "1111128",
    poDate: "08/13/24",
    shipTo: "Location Name R",
    amount: "$130.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111128",
  },
  {
    key: "112",
    salesOrder: "1111111",
    poDate: "08/13/24",
    shipTo: "Location Name A",
    amount: "$325.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111111",
  },
  {
    key: "212",
    salesOrder: "1111112",
    poDate: "08/13/24",
    shipTo: "Location Name B",
    amount: "$215.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111112",
  },
  {
    key: "312",
    salesOrder: "1111113",
    poDate: "08/13/24",
    shipTo: "Location Name C",
    amount: "$140.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111113",
  },
  {
    key: "412",
    salesOrder: "1111114",
    poDate: "08/13/24",
    shipTo: "Location Name D",
    amount: "$49.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111114",
  },
  {
    key: "512",
    salesOrder: "1111115",
    poDate: "08/13/24",
    shipTo: "Location Name E",
    amount: "$64.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111115",
  },
  {
    key: "612",
    salesOrder: "1111116",
    poDate: "08/13/24",
    shipTo: "Location Name F",
    amount: "$72.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111116",
  },
  {
    key: "712",
    salesOrder: "1111117",
    poDate: "08/13/24",
    shipTo: "Location Name G",
    amount: "$25.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111117",
  },
  {
    key: "812",
    salesOrder: "1111118",
    poDate: "08/13/24",
    shipTo: "Location Name H",
    amount: "$80.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111118",
  },
  {
    key: "912",
    salesOrder: "1111119",
    poDate: "08/13/24",
    shipTo: "Location Name I",
    amount: "$300.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111119",
  },
  {
    key: "1012",
    salesOrder: "1111120",
    poDate: "08/13/24",
    shipTo: "Location Name J",
    amount: "$500.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111120",
  },
  {
    key: "1112",
    salesOrder: "1111121",
    poDate: "08/13/24",
    shipTo: "Location Name K",
    amount: "$150.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111121",
  },
  {
    key: "1212",
    salesOrder: "1111122",
    poDate: "08/13/24",
    shipTo: "Location Name L",
    amount: "$200.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111122",
  },
  {
    key: "1312",
    salesOrder: "1111123",
    poDate: "08/13/24",
    shipTo: "Location Name M",
    amount: "$420.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.REJECTED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.CANCELED],
    customerPO: "1111123",
  },
  {
    key: "1412",
    salesOrder: "1111124",
    poDate: "08/13/24",
    shipTo: "Location Name N",
    amount: "$65.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.APPROVED],
    shipStatus: STATUSES_SHIPS[IStatusesShip.SHIPPED],
    customerPO: "1111124",
  },
  {
    key: "1512",
    salesOrder: "1111125",
    poDate: "08/13/24",
    shipTo: "Location Name O",
    amount: "$115.00",
    approvalStatus: STATUSES_APPROVAL[IStatusesApproval.PENDING],
    shipStatus: STATUSES_SHIPS[IStatusesShip.PENDING],
    customerPO: "1111125",
  },
];

export const LOCATION_DATA: ILocation[] = [
  {
    slug: "central-warehouse",
    location_name: "Central Warehouse",
    address_1: "123 Main Street",
    address_2: "123 Main Street",
    city: "Springfield",
    state: "IL",
    zip_code: "62704",
    contact_name: "John Doe",
    contact_email: "johndoe@example.com",
    buyer_name: "Alice Smith",
    buyer_email: "alice.smith@example.com",
  },
  {
    slug: "downtown-office",
    location_name: "Downtown Office",
    address_1: "456 Elm Street",
    address_2: "123 Main Street",
    city: "Chicago",
    state: "IL",
    zip_code: "60614",
    contact_name: "Jane Roe",
    contact_email: "janeroe@example.com",
    buyer_name: "Bob Johnson",
    buyer_email: "bob.johnson@example.com",
  },
  {
    slug: "east-coast-hub",
    location_name: "East Coast Hub",
    address_1: "789 Ocean Drive",
    address_2: "123 Main Street",
    city: "Miami",
    state: "FL",
    zip_code: "33139",
    contact_name: "Emily Davis",
    contact_email: "emily.davis@example.com",
    buyer_name: "Charlie Brown",
    buyer_email: "charlie.brown@example.com",
  },
];
