import { IOptionSelect } from "src/@types/form";
import { Column, Row } from "../Table/types";

export const SORT_OPTIONS: IOptionSelect[] = [
  { label: "select", value: "select" },
  { label: "Date: Newest First", value: "date_desc" },
  { label: "Date: Oldest First", value: "date_asc" },
  { label: "Name: A to Z", value: "name_asc" },
  { label: "Name: Z to A", value: "name_desc" },
  { label: "Price: Low to High", value: "price_asc" },
  { label: "Price: High to Low", value: "price_desc" },
];

export const columns: Column[] = [
  { key: "customerPO", label: "Customer PO #" },
  { key: "poDate", label: "PO Date" },
  { key: "salesOrder", label: "Sales Order #" },
  { key: "shipTo", label: "Ship To" },
  { key: "amount", label: "Amount" },
  { key: "approvalStatus", label: "Approval Status" },
  { key: "shipStatus", label: "Ship Status" },
];

export const rows: Row[] = [
  {
    key: "1",
    salesOrder: "1111111",
    poDate: "08/13/24",
    shipTo: "Location Name",
    amount: "$325.00",
    approvalStatus: "Approved",
    shipStatus: "Shipped",
    customerPO: "1111111",
  },
  {
    key: "2",
    customerPO: "1111112",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$215.00",
    approvalStatus: "Pending",
    shipStatus: "Pending",
  },
  {
    key: "3",
    customerPO: "1111113",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$140.00",
    approvalStatus: "Rejected",
    shipStatus: "Cancelled",
  },
  {
    key: "4",
    customerPO: "1111114",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$49.00",
    approvalStatus: "Approved",
    shipStatus: "Shipped",
  },
  {
    key: "5",
    customerPO: "1111115",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$64.00",
    approvalStatus: "Pending",
    shipStatus: "Pending",
  },
  {
    key: "6",
    customerPO: "1111116",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$72.00",
    approvalStatus: "Rejected",
    shipStatus: "Cancelled",
  },
  {
    key: "7",
    customerPO: "1111117",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$25.00",
    approvalStatus: "Approved",
    shipStatus: "Shipped",
  },
  {
    key: "8",
    customerPO: "1111118",
    poDate: "08/13/24",
    salesOrder: "1111111",
    shipTo: "Location Name",
    amount: "$80.00",
    approvalStatus: "Approved",
    shipStatus: "Pending",
  },
];
